spring:
  config:
    activate:
      on-profile: "dev"
build:
  version: "4.0"

cards:
  message: "Welcome to EazyBank CARDS related Dev APIs"
  contactDetails:
    name: "John Doe - Developer"
    email: "john-cards@eazybank.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1234
