spring:
  config:
    activate:
      on-profile: "qa"

build:
  version: "3.0"

accounts:
  message: "Welcome to EazyBank accounts related QA APIs"
  contactDetails:
    name: "John Doe - Developer"
    email: "john@eazybank.com"
  onCallSupport:
    - (555) 555-2345
    - (555) 523-2345