spring:
  config:
    activate:
      on-profile: "qa"

build:
  version: "3.0"

loans:
  message: "Welcome to EazyBank LOANS related QA APIs"
  contactDetails:
    name: "John Doe - Developer"
    email: "john-loans@eazybank.com"
  onCallSupport:
    - (555) 555-2345
    - (555) 523-2345